# -*- coding: utf-8 -*-
"""QnA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rMB6D4t5UPyoeq94xEleszbPwXlkwp6U
"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch
model_name = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

context = """
Artificial intelligence is a branch of computer science that aims to create
systems capable of performing tasks that typically require human intelligence.
"""

question = "What is artificial intelligence?"

input_text = f"answer the question based on the context.\ncontext: {context}\nquestion: {question}"

input_ids = tokenizer(
    input_text,
    return_tensors="pt",
    max_length=512,
    truncation=True
).input_ids.to(device)

outputs = model.generate(
    input_ids,
    max_length=64,
    num_beams=4,
    early_stopping=True
)

answer = tokenizer.decode(outputs[0], skip_special_tokens=True)

print("Question:", question)
print("Answer:", answer)

